### ISSUE TITLE
Strings with embedded handlebars passed as arguments don't work

### ISSUE THREAD

**Issue by wagenet** [lifeart/els-addon-typed-templates#67]
```hbs
<MyComponent
  @value="my-value {{if this.otherValue this.otherValue "missing"}}" />
```

Causes:

```
Cannot find name 'object'. Did you mean 'Object'?
```

**Comment by lifeart** [comment]
should work in `v4.2.1`
